name: 'Setup Stg-Cli'
description: 'Setup Stg-Cli environment for system'

inputs:
  working-directory:
    description: 'The directory to set as the default working directory'
    required: false
    
runs:
  using: 'node12'
  main: 'index.js'