name: 'Setup Stg-Cli'
description: 'Setup Stg-Cli environment for system'

inputs:
  branch:
    description: 'The branch to pull from'
    required: true
    default: 'main'
    
runs:
  using: 'composite'
  steps:
    - name: Load environment variables from .env
      run: |
        sed 's/^/export /' .env > /tmp/env.sh
        source /tmp/env.sh
        rm /tmp/env.sh
      shell: bash
    - name: Create GitHub App token
      uses: actions/create-github-app-token@v1
      id: create-token
      with:
        app_id: ${{ env.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
        permissions: 'write:packages, read:org'  # Adjust permissions as needed

    - name: Pull from branch
      run: |
       git pull origin ${{ inputs.branch }}
       echo ${{ steps.create-token.outputs.token }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}